version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: nestjs-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=sample
      - MYSQL_DATABASE=sample
      - MYSQL_USER=sample
      - MYSQL_PASSWORD=sample
      - TZ=Asia/Tokyo
    ports:
      - 3306:3306
    volumes:
      - db-store:/var/lib/mysql
      - ./conf:/etc/mysql/conf.d

volumes:
  db-store:
